import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Test Vault plugin path
const testVaultPath = 'Test Vault/.obsidian/plugins/podcast-player';

// Ensure output directory exists
if (!fs.existsSync(testVaultPath)) {
	fs.mkdirSync(testVaultPath, { recursive: true });
}

// Copy manifest and styles to Test Vault after build
const copyToTestVault = () => {
	const filesToCopy = ['manifest.json', 'styles.css'];
	filesToCopy.forEach(file => {
		if (fs.existsSync(file)) {
			const dest = path.join(testVaultPath, file);
			fs.copyFileSync(file, dest);
			console.log(`✓ Copied ${file} to Test Vault`);
		}
	});
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${testVaultPath}/main.js`,
	minify: prod,
	plugins: [{
		name: 'copy-files',
		setup(build) {
			build.onEnd(() => {
				copyToTestVault();
			});
		}
	}]
});

if (prod) {
	await context.rebuild();
	console.log('✓ Production build complete');
	process.exit(0);
} else {
	await context.watch();
	console.log('👀 Watching for changes...');
	console.log(`📦 Output: ${testVaultPath}/main.js`);
}
