import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Test Vault plugin paths - support multiple test vaults
const testVaultPaths = [
	'Test Vault/.obsidian/plugins/podcast-player',
	'Podcast Test Vault/.obsidian/plugins/podcast-player'
];

// Primary output path (first vault)
const primaryVaultPath = testVaultPaths[0];

// Ensure all output directories exist
testVaultPaths.forEach(vaultPath => {
	if (!fs.existsSync(vaultPath)) {
		fs.mkdirSync(vaultPath, { recursive: true });
		console.log(`✓ Created directory: ${vaultPath}`);
	}
});

// Copy manifest and styles to all Test Vaults after build
const copyToTestVaults = () => {
	const filesToCopy = ['manifest.json', 'styles.css'];

	testVaultPaths.forEach(vaultPath => {
		filesToCopy.forEach(file => {
			if (fs.existsSync(file)) {
				const dest = path.join(vaultPath, file);
				fs.copyFileSync(file, dest);
			}
		});

		// Copy main.js from primary vault to other vaults
		if (vaultPath !== primaryVaultPath) {
			const sourceMainJs = path.join(primaryVaultPath, 'main.js');
			const destMainJs = path.join(vaultPath, 'main.js');
			if (fs.existsSync(sourceMainJs)) {
				fs.copyFileSync(sourceMainJs, destMainJs);
			}
		}
	});

	console.log(`✓ Copied files to ${testVaultPaths.length} test vault(s)`);
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${primaryVaultPath}/main.js`,
	minify: prod,
	plugins: [{
		name: 'copy-files',
		setup(build) {
			build.onEnd(() => {
				copyToTestVaults();
			});
		}
	}]
});

if (prod) {
	await context.rebuild();
	console.log('✓ Production build complete');
	process.exit(0);
} else {
	await context.watch();
	console.log('👀 Watching for changes...');
	console.log(`📦 Primary output: ${primaryVaultPath}/main.js`);
	console.log(`📦 Syncing to ${testVaultPaths.length} vault(s)`);
}

