/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var l=Object.defineProperty;var t=Object.getOwnPropertyDescriptor;var i=Object.getOwnPropertyNames;var P=Object.prototype.hasOwnProperty;var r=(a,o)=>{for(var d in o)l(a,d,{get:o[d],enumerable:!0})},g=(a,o,d,c)=>{if(o&&typeof o=="object"||typeof o=="function")for(let e of i(o))!P.call(a,e)&&e!==d&&l(a,e,{get:()=>o[e],enumerable:!(c=t(o,e))||c.enumerable});return a};var m=a=>g(l({},"__esModule",{value:!0}),a);var p={};r(p,{default:()=>s});module.exports=m(p);var n=require("obsidian"),s=class extends n.Plugin{async onload(){console.log("Loading Podcast Player plugin"),this.addRibbonIcon("podcast","Podcast Player",o=>{new n.Notice("Podcast Player - Coming Soon!")}),this.addCommand({id:"open-podcast-player",name:"Open Podcast Player",callback:()=>{new n.Notice("Podcast Player view - Coming Soon!")}}),this.addCommand({id:"subscribe-to-podcast",name:"Subscribe to Podcast",callback:()=>{new n.Notice("Subscribe to Podcast - Coming Soon!")}}),console.log("Podcast Player plugin loaded successfully")}onunload(){console.log("Unloading Podcast Player plugin")}};
